# Generated by Django 4.1 on 2022-09-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarangMyWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchedFilm', models.CharField(max_length=50)),
                ('titleWatched', models.TextField()),
                ('ratingWatched', models.TextField()),
                ('releaseDateWatched', models.TextField()),
                ('reviewWatched', models.TextField()),
            ],
        ),
    ]
